stl_container_test: main.cpp test_array.hpp test_vector.hpp test_list.hpp test_forwardlist.hpp test_slist.hpp test_deque.hpp test_stack.hpp test_multiset.hpp test_multimap.hpp test_unordered_multiset.hpp test_unordered_multimap.hpp test_set.hpp test_map.hpp test_unordered_set.hpp test_unordered_map.hpp pub.h	
	g++ -o $@ $< -std=c++11 
clean:
	rm main_test *.o
